import {
  buildClauseKey,
  type CatalogRequirement,
  type IsoStandardCode,
} from "@/domain/ims/catalog";

function req(
  standard: IsoStandardCode,
  clauseCode: string,
  title: string,
  summary: string,
  essential: boolean,
  tags: string[],
): CatalogRequirement {
  return {
    standard,
    clauseCode,
    clauseKey: buildClauseKey(standard, clauseCode),
    title,
    summary,
    essential,
    tags,
  };
}

/**
 * Essential + scalable starter set for MVP templates.
 * Not the full ISO text — curated clauses for greenfield baselines.
 */
export const ESSENTIAL_CATALOG_SEED: CatalogRequirement[] = [
  // —— ISO 9001 ——
  req(
    "ISO9001",
    "4.1",
    "Comprensión de la organización y su contexto",
    "Determinar cuestiones internas y externas relevantes al SGC.",
    true,
    ["contexto", "planificacion"],
  ),
  req(
    "ISO9001",
    "4.2",
    "Necesidades y expectativas de las partes interesadas",
    "Identificar partes interesadas y sus requisitos pertinentes.",
    true,
    ["contexto", "partes-interesadas"],
  ),
  req(
    "ISO9001",
    "5.1",
    "Liderazgo y compromiso",
    "Demostrar liderazgo y compromiso con el SGC.",
    true,
    ["liderazgo"],
  ),
  req(
    "ISO9001",
    "6.1",
    "Acciones para abordar riesgos y oportunidades",
    "Planificar acciones frente a riesgos y oportunidades.",
    true,
    ["riesgos", "planificacion"],
  ),
  req(
    "ISO9001",
    "7.5",
    "Información documentada",
    "Controlar la creación y actualización de información documentada.",
    true,
    ["documentos"],
  ),
  req(
    "ISO9001",
    "8.1",
    "Planificación y control operacional",
    "Planificar, implementar y controlar procesos operativos.",
    true,
    ["operacion"],
  ),
  req(
    "ISO9001",
    "9.2",
    "Auditoría interna",
    "Realizar auditorías internas a intervalos planificados.",
    true,
    ["auditoria", "evaluacion"],
  ),
  req(
    "ISO9001",
    "10.2",
    "No conformidad y acción correctiva",
    "Reaccionar ante no conformidades y tomar acciones correctivas.",
    true,
    ["mejora", "nc"],
  ),
  req(
    "ISO9001",
    "8.5.1",
    "Control de la producción y de la provisión del servicio",
    "Controlar condiciones controladas de producción/servicio.",
    false,
    ["operacion", "escalable"],
  ),

  // —— ISO 14001 ——
  req(
    "ISO14001",
    "4.1",
    "Comprensión de la organización y de su contexto",
    "Determinar cuestiones ambientales internas y externas.",
    true,
    ["contexto", "ambiente"],
  ),
  req(
    "ISO14001",
    "6.1.2",
    "Aspectos ambientales",
    "Determinar aspectos ambientales y sus impactos.",
    true,
    ["aspectos", "ambiente"],
  ),
  req(
    "ISO14001",
    "6.1.3",
    "Requisitos legales y otros requisitos",
    "Determinar y acceder a requisitos legales ambientales.",
    true,
    ["legal", "ambiente"],
  ),
  req(
    "ISO14001",
    "7.5",
    "Información documentada",
    "Controlar información documentada del SGA.",
    true,
    ["documentos", "ambiente"],
  ),
  req(
    "ISO14001",
    "8.1",
    "Planificación y control operacional",
    "Establecer controles operacionales ambientales.",
    true,
    ["operacion", "ambiente"],
  ),
  req(
    "ISO14001",
    "8.2",
    "Preparación y respuesta ante emergencias",
    "Prepararse y responder a emergencias ambientales.",
    true,
    ["emergencias", "ambiente"],
  ),
  req(
    "ISO14001",
    "9.1.1",
    "Seguimiento, medición, análisis y evaluación",
    "Hacer seguimiento del desempeño ambiental.",
    true,
    ["indicadores", "ambiente"],
  ),
  req(
    "ISO14001",
    "10.2",
    "No conformidad y acción correctiva",
    "Tratar no conformidades ambientales.",
    true,
    ["mejora", "nc", "ambiente"],
  ),
  req(
    "ISO14001",
    "6.2",
    "Objetivos ambientales y planificación",
    "Establecer objetivos ambientales y planes para lograrlos.",
    false,
    ["objetivos", "escalable", "ambiente"],
  ),

  // —— ISO 45001 ——
  req(
    "ISO45001",
    "4.1",
    "Comprensión de la organización y de su contexto",
    "Determinar cuestiones relevantes para SST.",
    true,
    ["contexto", "sst"],
  ),
  req(
    "ISO45001",
    "5.1",
    "Liderazgo y compromiso",
    "Liderazgo y compromiso con el SG-SST.",
    true,
    ["liderazgo", "sst"],
  ),
  req(
    "ISO45001",
    "6.1.2",
    "Identificación de peligros y evaluación de riesgos",
    "Identificar peligros y evaluar riesgos y oportunidades SST.",
    true,
    ["riesgos", "sst"],
  ),
  req(
    "ISO45001",
    "7.5",
    "Información documentada",
    "Controlar información documentada del SG-SST.",
    true,
    ["documentos", "sst"],
  ),
  req(
    "ISO45001",
    "8.1.2",
    "Eliminar peligros y reducir riesgos SST",
    "Aplicar jerarquía de controles.",
    true,
    ["operacion", "sst"],
  ),
  req(
    "ISO45001",
    "8.2",
    "Preparación y respuesta ante emergencias",
    "Prepararse y responder a emergencias SST.",
    true,
    ["emergencias", "sst"],
  ),
  req(
    "ISO45001",
    "9.1.1",
    "Seguimiento, medición, análisis y evaluación",
    "Hacer seguimiento del desempeño SST.",
    true,
    ["indicadores", "sst"],
  ),
  req(
    "ISO45001",
    "10.2",
    "Incidente, no conformidad y acción correctiva",
    "Investigar incidentes y no conformidades SST.",
    true,
    ["mejora", "nc", "sst"],
  ),
  req(
    "ISO45001",
    "5.4",
    "Consulta y participación de los trabajadores",
    "Consultar y hacer participar a los trabajadores.",
    false,
    ["participacion", "escalable", "sst"],
  ),
];
